### ISSUE TITLE
settings not save ?

### ISSUE THREAD

**Issue by monado1110** [originalnicodr/RELit#10]
i have created a few new spotlight but when i restart the game they are gone, those don't saved ? same for scene light, i turn it off but when i change location it's back on again

**Comment by originalnicodr** [comment]
Light objects are created and stored in memory. Serializing them and loading them automatically on the scene would certainly not be trivial, and out of the scope of this project, since RELit is mainly for relighting static scenes.

When you turn off scene lights, the script will look up the already existing light objects made by the game and turn them off. But if you keep playing the game and change areas the light objects we turned off before will be deleted, and if you load the past area again they will be created again with the properties the game wants them to have, so you will indeed have to turn them off again. As said before, the objective of RELit is to set up static scenes, not really for gameplay purposes.

**Comment by monado1110** [comment]
> Light objects are created and stored in memory. Serializing them and loading them automatically on the scene would certainly not be trivial, and out of the scope of this project, since RELit is mainly for relighting static scenes.
> 
> When you turn off scene lights, the script will look up the already existing light objects made by the game and turn them off. But if you keep playing the game and change areas the light objects we turned off before will be deleted, and if you load the past area again they will be created again with the properties the game wants them to have, so you will indeed have to turn them off again. As said before, the objective of RELit is to set up static scenes, not really for gameplay purposes.

i see thanks for the explanation
